name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{secrets.NUGET_API_KEY}}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /property:Version=1.0.0
    - name: Publish To Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: wre.hubspot.apiclient/wre.hubspot.apiclient.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
